#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Siromi463 kimimi.nyan@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans1 = 0.0
ans2 = 1.0 
ans3 = 100.0
ans4 = 100.0
sum_ans = 0.0

sum_char_code1=0

for line in sys.stdin:
    line = line.rstrip()


    try:

        ans1 += float(line)
        ans2 *= float(line)
        ans3 -= float(line)
        ans4 /= float(line)

    except:

        list_char1 = list(line)
        for n in list_char1:
            sum_char_code1 += ord(n)

        print("入力された文字列の各Unicodeの合計:{}".format(sum_char_code1))
        sys.exit()

sum_ans = ans1 + ans2 + ans3 + ans4
print("標準入力の合計値：{}".format(ans1))
print("標準入力の乗算値：{}".format(ans2))
print("標準入力の合計値を１００から引いた値：{}".format(ans3))
print("標準入力で１００を割っていった最終値：{}".format(ans4))
print("上四つの合計値：{}".format(sum_ans))
