#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Fujioka Kimiyasu kimimi.nyan@gmail.com

import sys

ans = 0.0
for line in sys.stdin:
    line = line.rstrip()

    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
